---
- name: Install pyenv
  hosts: all
  remote_user: centos
  become: true

  vars_files:
    - defaults/main.yml
    # - 'vars/main.yml'

  vars:
    python_virtualenvs:
      - name: latest
        version: 3.6.5

  tasks:
    - import_tasks: tasks/main.yml

